import mongoose from 'mongoose';

const Schema = mongoose.Schema;

const userSchema = new Schema({
    firstName: {
        type: String,
        required: true,
    },
    lastName: {
        type: String,
        required: true,
    },
    email: {
        type: String,
        required: true,
    },
    password: {
        type: String,
        required: true,
    },
    education: {
        schoolName: { type: String },
        degree: { type: String },
        major: { type: String },
        startDate: { type: Date },
        endDate: { type: Date },
    },
    professionalExperience: {
        employerName: { type: String },
        position: { type: String },
        startDate: { type: Date },
        endDate: { type: Date },
    },
    interests: {
        type: Map,
        of: String,
        default: {
            'Full-Stack Developement': '0',
            'Machine Learning': '0',
            'Deep Learning': '0',
            'Data Science': '0',
            'Software Testing': '0',
            'Product Management': '0',
            'Project Managaement': '0',
            'Cloud Computing': '0',
            'Backend Developement': '0',
            'UIUX Design': '0',
        },
    },
    skills: {
        type: Array,
        required: true,
        default: [
            'python',
            'pytorch',
            'sql',
            'mxnet',
            'mlflow',
            'einstein',
            'theano',
            'pyspark',
            'solr',
            'mahout',
            'cassandra',
            'aws',
            'powerpoint',
            'spark',
            'pig',
            'sas',
            'java',
            'nosql',
            'docker',
            'salesforce',
            'scala',
            'r',
            'c',
            'c++',
            'net',
            'tableau',
            'pandas',
            'scikitlearn',
            'sklearn',
            'matlab',
            'scala',
            'keras',
            'tensorflow',
            'clojure',
            'caffe',
            'scipy',
            'numpy',
            'matplotlib',
            'vba',
            'spss',
            'linux',
            'azure',
            'cloud',
            'gcp',
            'mongodb',
            'mysql',
            'oracle',
            'redshift',
            'snowflake',
            'kafka',
            'javascript',
            'qlik',
            'jupyter',
            'perl',
            'bigquery',
            'unix',
            'react',
            'scikit',
            'powerbi',
            's3',
            'ec2',
            'lambda',
            'ssrs',
            'kubernetes',
            'hana',
            'spacy',
            'tf',
            'django',
            'sagemaker',
            'seaborn',
            'mllib',
            'github',
            'git',
            'elasticsearch',
            'splunk',
            'airflow',
            'looker',
            'rapidminer',
            'birt',
            'pentaho',
            'jquery',
            'nodejs',
            'd3',
            'plotly',
            'bokeh',
            'xgboost',
            'rstudio',
            'shiny',
            'dash',
            'h20',
            'h2o',
            'hadoop',
            'mapreduce',
            'hive',
            'cognos',
            'angular',
            'nltk',
            'flask',
            'node',
            'firebase',
            'bigtable',
            'rust',
            'php',
            'cntk',
            'lightgbm',
            'kubeflow',
            'rpython',
            'unixlinux',
            'postgressql',
            'postgresql',
            'postgres',
            'hbase',
            'dask',
            'ruby',
            'julia',
            'tensor',
            'dplyr',
            'ggplot2',
            'esquisse',
            'bioconductor',
            'shiny',
            'lubridate',
            'knitr',
            'mlr',
            'quanteda',
            'dt',
            'rcrawler',
            'caret',
            'rmarkdown',
            'leaflet',
            'janitor',
            'ggvis',
            'plotly',
            'rcharts',
            'rbokeh',
            'broom',
            'stringr',
            'magrittr',
            'slidify',
            'rvest',
            'rmysql',
            'rsqlite',
            'prophet',
            'glmnet',
            'text2vec',
            'snowballc',
            'quantmod',
            'rstan',
            'swirl',
            'datascience',
            'amazon web services',
            'google cloud',
            'sql server',
            'statistics',
            'cleansing',
            'chatbot',
            'cleaning',
            'blockchain',
            'causality',
            'correlation',
            'bandit',
            'anomaly',
            'kpi',
            'dashboard',
            'geospatial',
            'ocr',
            'econometrics',
            'pca',
            'gis',
            'svm',
            'svd',
            'tuning',
            'hyperparameter',
            'hypothesis',
            'salesforcecom',
            'segmentation',
            'biostatistics',
            'unsupervised',
            'supervised',
            'exploratory',
            'recommender',
            'recommendations',
            'research',
            'sequencing',
            'probability',
            'reinforcement',
            'graph',
            'bioinformatics',
            'chi',
            'knn',
            'outlier',
            'etl',
            'normalization',
            'classification',
            'optimizing',
            'prediction',
            'forecasting',
            'clustering',
            'cluster',
            'optimization',
            'visualization',
            'nlp',
            'c#',
            'regression',
            'logistic',
            'nn',
            'cnn',
            'glm',
            'rnn',
            'lstm',
            'gbm',
            'boosting',
            'recurrent',
            'convolutional',
            'bayesian',
            'bayes',
            'random forest',
            'natural language processing',
            'machine learning',
            'decision tree',
            'deep learning',
            'experimental design',
            'time series',
            'nearest neighbors',
            'neural network',
            'support vector machine',
            'computer vision',
            'machine vision',
            'dimensionality reduction',
            'text analytics',
            'power bi',
            'a/b testing',
            'ab testing',
            'chat bot',
            'data mining',
            'AWS',
            'Terraform',
            'Packer',
            'Puppet',
            'Ansible',
            'Docker',
            'Consul',
            'Vault',
            'Git',
            'Gitlab',
            'Bitbucket',
            'Jenkins',
            'Confluence',
            'Jira',
            'Datadog',
            'Nagios',
            'Splunk',
            'New Relic',
            'LogicMonitor',
            'Kong API',
            'Apache Solr',
            'Varnish',
            'Nginx',
            'Hadoop',
            'Hive',
            'HDFS',
            'Xen Virtualization',
            'Bash scripting',
            'python scripting',
            'Mysql',
            'Postgress',
            'Outstanding Communication Skills',
            'Basic Technical Expertise',
            'Deep Business Skills',
            'Research Abilities',
            'Analytical Skills',
            'Interpersonal Abilities',
            'Marketing and Sales Abilities',
            'Delegation Skills',
            'Strategic Thinking',
            'Prioritization skills',
            'Communication',
            'Leadership',
            'Organization',
            'Negotiation',
            'Team management',
            'Time management',
            'Risk management',
            'Problem-solving',
            'Budget management',
            'Motivation',
            'Technical writing',
            'Adaptability',
            'Technical skills',
            'Reporting skills',
            'Active listening',
            'Research skills',
            'Interpersonal skills',
            'Project management methodologies',
            'Policy knowledge',
            'Conflict management',
        ],
    },
    status: {
        type: Boolean,
        default: true,
    },
    connections: {
        type: Array,
        default: [],
    },
    timeStamp: {
        type: Date,
        default: Date.now,
    },
    ratings: {
        type: Number,
        default: 0,
    },
});

const User = mongoose.model('user', userSchema);

export default User;
